##################################################################################
# pre-commit configuration file
# Go to https://pre-commit.com for more information
# Go to https://pre-commit.com/hooks.html for info on pre-commit hooks supported
##################################################################################

default_stages: [commit, manual]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: trailing-whitespace
            exclude: "^tests/"
          - id: end-of-file-fixer
            exclude: "^tests/"
          - id: check-yaml
            exclude: "^tests/"
            args: ['--unsafe']
          - id: check-json
            exclude: "^tests/"
          - id: check-toml
          - id: check-added-large-files
            args: ['--maxkb=10000']
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: debug-statements
            exclude: "^tests/"

    - repo: https://github.com/ibm/detect-secrets
    # If you desire to use a specific version of detect-secrets, you can replace `master` with other git revisions such as branch, tag or commit sha.
    # You are encouraged to use static refs such as tags, instead of branch name
    #
    # Running "pre-commit autoupdate" automatically updates rev to latest tag
      rev: 0.13.1+ibm.61.dss
      hooks:
        - id: detect-secrets # pragma: whitelist secret
          # Add options for detect-secrets-hook binary. You can run `detect-secrets-hook --help` to list out all possible options.
          # You may also run `pre-commit run detect-secrets` to preview the scan result.
          # when "--baseline" without "--use-all-plugins", pre-commit scan with just plugins in baseline file
          # when "--baseline" with "--use-all-plugins", pre-commit scan with all available plugins
          # add "--fail-on-unaudited" to fail pre-commit for unaudited potential secrets
          args: [--baseline, .secrets.baseline, --use-all-plugins]

    - repo: local
      hooks:
        - id: black
          name: "black"
          language: system
          types: [python]
          exclude: ^tests/
          entry: black
          args: ["--diff"]

        - id: isort
          name: "isort"
          language: system
          types: [python]
          exclude: ^tests/
          entry: isort
          args: ["--profile", "black"]

        - id: flake8
          args:
            - "--max-line-length=120"
            - "--ignore=W503"
          name: "flake8"
          language: system
          types: [python]
          exclude: ^tests/
          entry: flake8

        - id: bandit
          name: "bandit"
          language: system
          types: [python]
          exclude: ^tests/
          entry: bandit
          args: ["-c", "pyproject.toml"]
