##################################################################################
# pre-commit configuration file
# Go to https://pre-commit.com for more information
# Go to https://pre-commit.com/hooks.html for info on pre-commit hooks supported
##################################################################################

default_stages: [commit, manual]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements

  - repo: local
    hooks:
      - id: black
        name: "black"
        language: system
        types: [python]
        files: ^src/
        entry: black
        args: ["--diff"]

      - id: isort
        name: "isort"
        language: system
        types: [python]
        entry: isort
        args: ["--profile", "black"]

      - id: flake8
        args:
          - "--max-line-length=120"
          - "--ignore=W503"
        name: "flake8"
        language: system
        types: [python]
        entry: flake8

      - id: bandit
        name: "bandit"
        language: system
        types: [python]
        entry: bandit
        args: ["-c", "pyproject.toml"]
